export const GET_CONATCT_LOAD = "GET_CONATCT_LOAD";
export const GET_CONATCT_SUCCESS = "GET_CONATCT_SUCCESS";
export const GET_CONATCT_FAIL = "GET_CONATCT_FAIL";

export const GET_ONE_CONTACT = "GET_ONE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";